areaId: 0

messages:
  prefix: "[Area]"
  cancelcreate: "땅 생성이 취소되었습니다."
  readytocreate: "블럭 두개를 좌클릭하여 땅을 생성할 범위를 지정하여 주세요."
  created: "%id%번 땅이 생성되었습니다."

  errors:
    unknown: "예상치못한 오류가 발생하였습니다."
    onlyplayer: "플레이어만 사용가능한 기능입니다."
    worldnotsame: "범위의 두 지점은 같은 월드여야 합니다."