name: AreaSystem
version: 1.0-SNAPSHOT
author: hwangseonu
main: me.mocha.area.AreaSystem
api-version: 1.16

commands:
  createarea:
    description: 땅을 생성합니다.
    usage: /createarea <height>
    permission: area.management.create

permissions:
  area.management.create:
    description: Allows to create area
    default: op
